package com.juner2026.crabpet;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;
public class PetService extends Service{
 WindowManager wm; FrameLayout root; WindowManager.LayoutParams lp; TextView bubble; CrabView crab; Handler h=new Handler(); int taps=0;
 public IBinder onBind(Intent i){return null;}
 public int onStartCommand(Intent i,int f,int id){show(); return START_STICKY;}
 void show(){if(root!=null)return; wm=(WindowManager)getSystemService(WINDOW_SERVICE); root=new FrameLayout(this); crab=new CrabView(this); root.addView(crab,new FrameLayout.LayoutParams(160,160)); bubble=new TextView(this); bubble.setText("你好呀");bubble.setTextColor(Color.rgb( ninety(), sixty(), seventy()));bubble.setTextSize(14);bubble.setPadding(22,12,22,12); GradientDrawable bg=new GradientDrawable();bg.setColor(Color.rgb(255,235,244));bg.setStroke(2,Color.rgb(238,165,192));bg.setCornerRadius(28);bubble.setBackground(bg);FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-2,70);bp.leftMargin=78;bp.topMargin=0;root.addView(bubble,bp);lp=new WindowManager.LayoutParams(360,170,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,PixelFormat.TRANSLUCENT);lp.gravity=Gravity.TOP|Gravity.START;lp.x=25;lp.y=230;wm.addView(root,lp);say("今天也要陪你"); }
 int ninety(){return 90;}int sixty(){return 65;}int seventy(){return 70;}
 void say(String s){if(bubble!=null){bubble.setText(s);bubble.setVisibility(View.VISIBLE);h.removeCallbacksAndMessages(null);h.postDelayed(()->{if(bubble!=null)bubble.setVisibility(View.GONE);},3800);}}
 public void onDestroy(){if(root!=null)wm.removeView(root);super.onDestroy();}
 class CrabView extends View{Paint p=new Paint();float downX,downY;long down;int frame=0;Runnable run=()->{frame++;invalidate();h.postDelayed(()->run.run(),180);};CrabView(Context c){super(c);p.setAntiAlias(false);h.post(run);}
 void box(Canvas c,int x,int y,int w,int h,int col){p.setColor(col);c.drawRect(x,y,x+w,y+h,p);}
 protected void onDraw(Canvas c){super.onDraw(c);int bob=(int)(Math.sin(frame*.7)*3), dark=Color.rgb(183, sixty(), ninety()), mid=Color.rgb(239,112,145), light=Color.rgb(255,174,192), ink=Color.rgb(67,45,55); box(c,48,55+bob,64,58,mid);box(c,38,65+bob,84,42,mid);box(c,28,76+bob,104,24,mid);box(c,20,70+bob,16,12,dark);box(c,124,70+bob,16,12,dark);box(c,8,82+bob,22,10,dark);box(c,130,82+bob,22,10,dark);box(c,43,46+bob,12,22,light);box(c,105,46+bob,12,22,light);box(c,47,69+bob,12,12,ink);box(c,101,69+bob,12,12,ink);box(c,50,71+bob,4,4,Color.WHITE);box(c,104,71+bob,4,4,Color.WHITE);box(c,58,96+bob,44,6,Color.rgb(198,67,101));int leg=frame%2==0?0:4;box(c,40,112+bob,14,16,dark);box(c,58,115+bob+leg,12,18,dark);box(c,102,115+bob-leg,12,18,dark);box(c,118,112+bob,14,16,dark);box(c,54,134+bob,18,6,ink);box(c,94,134+bob,18,6,ink);}
 public boolean onTouchEvent(MotionEvent e){if(e.getAction()==0){down=System.currentTimeMillis();downX=e.getRawX()-lp.x;downY=e.getRawY()-lp.y;return true;}if(e.getAction()==2){lp.x=(int)(e.getRawX()-downX);lp.y=(int)(e.getRawY()-downY);wm.updateViewLayout(root,lp);return true;}if(e.getAction()==1){long d=System.currentTimeMillis()-down;if(d>700){say("我先藏两秒");root.setVisibility(INVISIBLE);h.postDelayed(()->root.setVisibility(VISIBLE),2000);}else{taps++;say(taps>1?"被你连戳啦": "戳我干嘛");h.postDelayed(()->taps=0,700);}return true;}return true;}}
}